# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
import numpy as np

arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(2, 5)

print(newarr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [30]:
import numpy as np

arr1 = np.array([[0,1, 2, 3,4],
                 [5,6,7,8,9],
                 [4, 6, 8, 9, 10],
                 [8, 9, 9, 8, 10]])

arr = np.vstack((arr1))

print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 4  6  8  9 10]
 [ 8  9  9  8 10]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [35]:
import numpy as np

arr1 = np.array([[1, 2, 3,4,5,6,7,8,9,10],[4, 5, 6,7,8,9,10,11,12]])


arr = np.hstack((arr1))

print(arr)

[ 1  2  3  4  5  6  7  8  9 10  4  5  6  7  8  9 10 11 12]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [46]:
import numpy as np

arr = np.array(([[1, 2, 3,],[4, 5, 6]]))

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [51]:
import numpy as np

arr = np.array([[1, 2, 3,], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [57]:
import numpy as np
arr=np.arange(25).reshape(5,5)
print(arr)
np.square (arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [59]:
import numpy as np
np.random.seed(123)
arr=np.random.randint(30,size=(5,6))
print(arr)
arr.mean()

[[13  2 28  2  6 17]
 [19 10 27 25 22  1]
 [ 0 17 15  9  0 14]
 [ 0 15 25 19 14 29]
 [ 4  0 16  4 17 23]]


13.1

## Question:9

### Find the standard deviation of the previous array in Q8?

In [66]:
import numpy as np
arr = np.std(123)
arr=np.random.randint(30,size=(5,6))
print(arr)
arr.mean()



[[ 3  2 20  7  2 20]
 [15 24 29 16  7  9]
 [ 3 28 28 20  6  1]
 [21 22 27  2  1 12]
 [ 8  3 10  5  0 11]]


12.066666666666666

## Question:10

### Find the median of the previous array in Q8?

In [67]:
import numpy as np
arr = np.std(123)
arr=np.random.randint(30,size=(5,6))
print(arr)
np.median(arr)

[[ 2 26 10 22 13 18]
 [ 4 15 11 27 29 12]
 [20  6 13 19 26 16]
 [ 6 14 20  7 11 22]
 [ 7  1 11 26  5 23]]


13.5

## Question:11

### Find the transpose of the previous array in Q8?

In [69]:
import numpy as np
arr = np.std(123)
arr=np.random.randint(30,size=(5,6))
arr
arr.T

array([[24, 19,  6, 20,  5],
       [ 6, 25, 17,  3,  8],
       [ 9,  6, 29,  1, 13],
       [23, 12, 14, 15, 22],
       [14, 22, 10, 13, 14],
       [ 6, 27,  3, 16, 15]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [72]:
import numpy as np 
array = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]]) 
print(n_array) 
trace = np.trace(n_array) 
print(trace) 

[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
196


## Question:13

### Find the determinant of the previous array in Q12?

In [79]:
import numpy as np
arry = np.array([[55, 25, 15, 41], 
                    [30, 44, 2, 54], 
                    [11, 45, 77, 11], 
                    [11, 212, 4, 20]])
print(arry)
result =  np.linalg.det(a)
print(result)


[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
-2.0000000000000004


## Question:14

### Find the 5th and 95th percentile of an array?

In [87]:
import numpy
arry = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

a = numpy.percentile(arry, 90)

print(a)
arry = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]
b = numpy.percentile(arry, 5)
print(b)

61.0
5.0


## Question:15

### How to find if a given array has any null values?

In [95]:
import numpy as np
array_sum = np.sum(array)
array_has_nan = np.isnan(array_sum)
print(array_has_nan)

False


In [96]:
import numpy as np
array_sum = np.sum(array)
array_has_nan = np.isnan(array_sum)
print(array)

[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
